//
//  EntryDetailsPresenter.swift
//  Renter
//
//  Created by Oleg Efimov on 17.01.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EntryDetailsPresentationLogic {
    func presentEntry(response: EntryDetails.GetEntry.Response)
}

class EntryDetailsPresenter: EntryDetailsPresentationLogic {
    weak var viewController: EntryDetailsDisplayLogic?

    // MARK: Parse and calc respnse from EntryDetailsInteractor and send simple view model to EntryDetailsViewController to be displayed

    func presentEntry(response: EntryDetails.GetEntry.Response) {
        let viewModel = EntryDetails.GetEntry.ViewModel()
        viewController?.displayEntry(viewModel: viewModel)
    }
//
//    func presentSomethingElse(response: EntryDetails.SomethingElse.Response) {
//        let viewModel = EntryDetails.SomethingElse.ViewModel()
//        viewController?.displaySomethingElse(viewModel: viewModel)
//    }
}
