//
//  EntryDetailsModels.swift
//  Renter
//
//  Created by Oleg Efimov on 17.01.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct EntrySectionViewModel {
    let title: String
    let rows: [EntryRowViewModel]
}

struct EntryRowViewModel {
    let title: String
    let value: String
}

enum EntryDetails {
    // MARK: Use cases

    enum GetEntry {
        struct Request {

        }

        struct Response {
            let entry: HistoryEntry
        }

        struct ViewModel {
            let sections: [EntrySectionViewModel]
        }
    }
    
//    enum SomethingElse
//    {
//        struct Request
//        {
//
//        }
//
//        struct Response
//        {
//
//        }
//
//        struct ViewModel
//        {
//
//        }
//    }
}
