//
//  EntryDetailsInteractor.swift
//  Renter
//
//  Created by Oleg Efimov on 17.01.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EntryDetailsBusinessLogic {
    func getEntry(request: EntryDetails.GetEntry.Request)
//    func doSomethingElse(request: EntryDetails.SomethingElse.Request)
}

protocol EntryDetailsDataStore {
    //var name: String { get set }
}

class EntryDetailsInteractor: EntryDetailsBusinessLogic, EntryDetailsDataStore {
    var presenter: EntryDetailsPresentationLogic?
    var worker: EntryDetailsWorker?
    //var name: String = ""

    // MARK: Do something (and send response to EntryDetailsPresenter)

    func getEntry(request: EntryDetails.GetEntry.Request) {
        worker = EntryDetailsWorker()
        worker?.doSomeWork()

        let response = EntryDetails.GetEntry.Response()
        presenter?.presentEntry(response: response)
    }
//
//    func doSomethingElse(request: EntryDetails.SomethingElse.Request) {
//        worker = EntryDetailsWorker()
//        worker?.doSomeOtherWork()
//
//        let response = EntryDetails.SomethingElse.Response()
//        presenter?.presentSomethingElse(response: response)
//    }
}
