//
//  AccountViewController.swift
//  Renter
//
//  Created by Oleg Efimov on 16.01.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AccountDisplayLogic: AnyObject {
    func displayUser(viewModel: Account.ShowUser.ViewModel)
    func displayUpdatedUsername(viewModel: Account.SaveUser.ViewModel)
    func displaySignOutAlert(viewModel: Account.SingOutUser.ViewModel)
    func displayError(with title: String, message: String)
}

class AccountViewController: UIViewController {
    
    var interactor: AccountBusinessLogic?
    
    var router: (NSObjectProtocol & AccountRoutingLogic & AccountDataPassing)?
    
    private var sections = [AccountSectionViewModel]()
    
    private let tableView: UITableView = {
        let tableView = UITableView(frame: .zero, style: .grouped)
        tableView.register(AccountTableViewCell.self,
                           forCellReuseIdentifier: AccountTableViewCell.identifier)
        return tableView
    }()

    // MARK: - View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        
        title = "Account"
        navigationController?.navigationBar.prefersLargeTitles = true
        view.backgroundColor = .systemBackground
        
        AccountConfigurator.shared.configure(with: self)
        
        configureViews()
        passUserRequest()
    }
    
    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        
        layoutViews()
    }
    
    //MARK: - receive events from UI
    
    
    // MARK: - request data from AccountInteractor

    func passUserRequest() {
        let request = Account.ShowUser.Request()
        interactor?.getUser(request: request)
    }

    func passUpdateNameRequest() {
//        let request = Account.SomethingElse.Request()
//        interactor?.updateUser(request: request)
    }
    
    // MARK: Common
    
    private func configureViews() {
        tableView.delegate = self
        tableView.dataSource = self
        
        view.addSubview(tableView)
    }

    private func layoutViews() {
        tableView.frame = view.bounds
    }

    private func displayUpdateNameModal(_ name: String) {
        let alert = ComponentFactory.shared.produceUIAlert(
            with: "Change name",
            message: "Enter your name",
            textFieldValue: name,
            placeholder: "Name...")
        
        alert.addAction(UIAlertAction(title: "Change",
                                      style: .default,
                                      handler: { [weak self] a in
            self?.interactor?.updateUserName(
                request: Account.SaveUser.Request(
                    name: alert.textFields?.first?.text ?? ""))
        }))
        
        present(alert, animated: true)
    }
    
}

// MARK: AccountDisplayLogic
extension AccountViewController: AccountDisplayLogic {
    // MARK: - display view model from AccountPresenter

    func displayUser(viewModel: Account.ShowUser.ViewModel) {
        DispatchQueue.main.async {
            self.sections = viewModel.sections
            self.tableView.reloadData()
        }
    }

    func displayUpdatedUsername(viewModel: Account.SaveUser.ViewModel) {
        guard let index = sections.firstIndex(where: { $0.rows.first?.tag == "name"})
        else { return }
        DispatchQueue.main.async { [weak self] in
            self?.sections[index] = viewModel.section
            self?.tableView.reloadSections([index], with: .automatic)
        }
    }
    
    func displaySignOutAlert(viewModel: Account.SingOutUser.ViewModel) {
        let alert = ComponentFactory.shared.produceUIAlert(
            with: viewModel.title,
            message: viewModel.message,
            action: UIAlertAction(
                title: "Sign Out",
                style: .destructive,
                handler: { [weak self] _ in
                    self?.interactor?.signOutUser()
                }))
        
        present(alert, animated: true)
    }
    
    func displayError(with title: String, message: String) {
        let alert = ComponentFactory.shared.produceUIAlert(
            with: title,
            message: message)
        
        present(alert, animated: true)
    }
}

// MARK: TableView
extension AccountViewController: UITableViewDelegate, UITableViewDataSource {
    
    func numberOfSections(in tableView: UITableView) -> Int {
        sections.count
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        sections[section].rows.count
    }
    
    func tableView(_ tableView: UITableView, titleForHeaderInSection section: Int) -> String? {
        sections[section].title
    }
    
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return 50
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        guard let cell = tableView.dequeueReusableCell(
            withIdentifier: AccountTableViewCell.identifier,
            for: indexPath) as? AccountTableViewCell
        else {
            return UITableViewCell()
        }
        let viewModel = sections[indexPath.section].rows[indexPath.row]
        cell.configure(with: viewModel)
        return cell
    }
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        tableView.deselectRow(at: indexPath, animated: true)
        let viewmodel = sections[indexPath.section].rows[indexPath.row]
        if viewmodel.tag == "logout" {
            interactor?.presentSignOutAlert()
        } else if viewmodel.tag == "name" {
            displayUpdateNameModal(viewmodel.content)
        }
    }
    
    func tableView(_ tableView: UITableView, willSelectRowAt indexPath: IndexPath) -> IndexPath? {
        let model = sections[indexPath.section].rows[indexPath.row]
        if model.isInteractable {
            return indexPath
        }
        return nil
    }
}
