//
//  AccountPresenter.swift
//  Renter
//
//  Created by Oleg Efimov on 16.01.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AccountPresentationLogic {
    func presentUser(response: Account.ShowUser.Response)
    func presentUpdatedUsername(response: Account.SaveUser.Response)
}

class AccountPresenter: AccountPresentationLogic {
    weak var viewController: AccountDisplayLogic?

    // MARK: Parse and calc respnse from AccountInteractor and send simple view model to AccountViewController to be displayed

    func presentUser(response: Account.ShowUser.Response) {
//        let viewModel = Account.ShowUser.ViewModel()
//        viewController?.displayUser(viewModel: viewModel)
    }
//
    func presentUpdatedUsername(response: Account.SaveUser.Response) {
//        let viewModel = Account.SaveUser.ViewModel()
//        viewController?.displayUpdatedUsername(viewModel: viewModel)
    }
}
