//
//  AccountModels.swift
//  Renter
//
//  Created by Oleg Efimov on 16.01.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct AccountSectionViewModel {
    let title: String
    let rows: [AccountRowViewModel]
}

struct AccountRowViewModel {
    let isInteractable: Bool
    let content: String
    let color: UIColor?
    let tag: String
}

enum Account {
    // MARK: Use cases

    enum ShowUser {
        struct Request {
        }

        struct Response {
            let user: User
        }

        struct ViewModel {
            let sections: [AccountSectionViewModel]
        }
    }
    
    enum SaveUser {
        struct Request {
            let name: String
        }

        struct Response {
            let user: User
        }

        struct ViewModel {
            let name: String
            let email: String
        }
    }
    
    enum SingOutUser {
        
        struct ViewModel {
            let title: String
            let message: String
        }
    }
}
