//
//  HistoryRouter.swift
//  Renter
//
//  Created by Oleg Efimov on 16.01.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HistoryRoutingLogic {
    func routeToEntryDetails()
    func routeToCreateNewEntry()
}

protocol HistoryDataPassing {
    var dataStore: HistoryDataStore? { get }
}

class HistoryRouter: NSObject, HistoryRoutingLogic, HistoryDataPassing {
    
    weak var viewController: HistoryViewController?
    
    var dataStore: HistoryDataStore?
    
    // MARK: Routing (navigating to other screens)
    
    func routeToEntryDetails() {
        let entryDetailsVC = EntryDetailsViewController()
        EntryDetailConfigurator.shared.configure(with: entryDetailsVC)
        guard var destinationDS = entryDetailsVC.router?.dataStore,
              let sourceDS = dataStore
        else {
            print("FAILED TO ROUTE")
            return
        }
        passDataToEntryDetails(source: sourceDS, destination: &destinationDS)
        viewController?.present(entryDetailsVC, animated: true)
    }
    
    func routeToCreateNewEntry() {
        let createNewEntryVC = CreateNewEntryViewController()
        CreateNewEntryConfigurator.shared.configure(with: createNewEntryVC)
        guard var destinationDS = createNewEntryVC.router?.dataStore,
              let sourceDS = dataStore
        else {
            return
        }
        passDataToCreateNewEntry(source: sourceDS, destination: &destinationDS)
        createNewEntryVC.modalPresentationStyle = .fullScreen
        viewController?.present(createNewEntryVC, animated: true)
    }
    
    // MARK: Passing data to other screen
    
    func passDataToEntryDetails(source: HistoryDataStore, destination: inout EntryDetailsDataStore) {
        guard let selected = viewController?.currentIndexPath,
              selected.count > 0
        else {
            return
        }
        destination.entry = source.historyEntries[selected[0].row]
    }
    
    func passDataToCreateNewEntry(source: HistoryDataStore, destination: inout CreateNewEntryDataStore) {
        guard let latestEntry = dataStore?.historyEntries.first else {
            return
        }
        let currentPlan = latestEntry.curPlan
        destination.actualPlan = currentPlan
    }
}
