//
//  HistoryWorker.swift
//  Renter
//
//  Created by Oleg Efimov on 16.01.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

protocol HistoryWorkerProtocol {
    func fetchHistoryData(completion: @escaping ([HistoryEntry]?) -> Void)
}

class HistoryWorker: HistoryWorkerProtocol {
    func calculateTotal() {
        
    }
    
    func fetchHistoryData(completion: @escaping ([HistoryEntry]?) -> Void) {
        ApiManager.shared.getHistoryData { result in
            switch result {
            case .success(let response):
                completion(response.entries.reversed())
            case .failure(_):
                //TODO: show some error
                completion(nil)
            }
        }
    }
}
