//
//  HistoryModels.swift
//  Renter
//
//  Created by Oleg Efimov on 16.01.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum History {
    // MARK: Use cases

    enum GetHistoryData {
        struct Request {

        }

        struct Response {

        }

        struct ViewModel {

        }
    }
    
    enum FilterData {
        struct Request {
            let startsAt: Date
            let endsAt: Date
        }

        struct Response {
            //models
        }

        struct ViewModel {

        }
    }
}
