//
//  HistoryPresenter.swift
//  Renter
//
//  Created by Oleg Efimov on 16.01.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HistoryPresentationLogic {
    func presentHistory(response: History.GetHistoryData.Response)
    func presentFiltredHistory(response: History.FilterData.Response)
}

class HistoryPresenter: HistoryPresentationLogic {
    weak var viewController: HistoryDisplayLogic?

    // MARK: Parse and calc respnse from HistoryInteractor and send simple view model to HistoryViewController to be displayed

    func presentHistory(response: History.GetHistoryData.Response) {
        let viewModel = History.GetHistoryData.ViewModel()
        viewController?.displayHistory(viewModel: viewModel)
    }

    func presentFiltredHistory(response: History.FilterData.Response) {
//        let viewModel = History.FilterData.ViewModel()
//        viewController?.displayFiltredHistory(viewModel: viewModel)
    }
}
