//
//  HistoryViewController.swift
//  Renter
//
//  Created by Oleg Efimov on 16.01.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HistoryDisplayLogic: AnyObject {
    func displayHistory(viewModel: History.GetHistoryData.ViewModel)
    func displayFiltredHistory(viewModel: History.FilterData.ViewModel)
}

class HistoryViewController: UIViewController, HistoryDisplayLogic {
    var interactor: HistoryBusinessLogic?
    var router: (NSObjectProtocol & HistoryRoutingLogic & HistoryDataPassing)?

    // MARK: - Routing

//    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
//        if let scene = segue.identifier {
//            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
//            if let router = router, router.responds(to: selector) {
//                router.perform(selector, with: segue)
//            }
//        }
//    }

    // MARK: - View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        
        title = "History"
        view.backgroundColor = .systemBackground
        
        HistoryConfigurator.shared.configure(with: self)
        
        passHistoryRequest()
    }
    
    //MARK: - receive events from UI
    
    
    
    // MARK: - request data from HistoryInteractor

    func passHistoryRequest() {
        let request = History.GetHistoryData.Request()
        interactor?.getHistory(request: request)
    }

    func passFilterRequest() {
//        let request = History.FilterData.Request()
//        interactor?.getFiltredHistory(request: request)
    }

    // MARK: - display view model from HistoryPresenter

    func displayHistory(viewModel: History.GetHistoryData.ViewModel) {
        //nameTextField.text = viewModel.name
    }

    func displayFiltredHistory(viewModel: History.FilterData.ViewModel) {
        // do sometingElse with viewModel
    }
}
