//
//  HistoryRouter.swift
//  Renter
//
//  Created by Oleg Efimov on 16.01.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HistoryRoutingLogic {
    func routeToEntryDetails()
}

protocol HistoryDataPassing {
    var dataStore: HistoryDataStore? { get }
}

class HistoryRouter: NSObject, HistoryRoutingLogic, HistoryDataPassing {
    weak var viewController: HistoryViewController?
    var dataStore: HistoryDataStore?

    // MARK: Routing (navigating to other screens)

    func routeToEntryDetails() {
        let entryDetailsVC = EntryDetailsViewController()
        EntryDetailConfigurator.shared.configure(with: entryDetailsVC)
        guard var destinationDS = entryDetailsVC.router?.dataStore,
              let sourceDS = dataStore
        else {
            print("FAILED TO ROUTE")
            return
        }
        passDataToEntryDetails(source: sourceDS, destination: &destinationDS)
        viewController?.present(entryDetailsVC, animated: true)
    }

// MARK: Navigation to other screen

//func navigateToSomewhere(source: HistoryViewController, destination: SomewhereViewController) {
//    source.show(destination, sender: nil)
//}

// MARK: Passing data to other screen

    func passDataToEntryDetails(source: HistoryDataStore, destination: inout EntryDetailsDataStore) {
        guard let indexPath = viewController?.currentIndexPath else {
            return
        }
        destination.entry = source.historyEntries[indexPath.row]
    }
}
