//
//  HistoryInteractor.swift
//  Renter
//
//  Created by Oleg Efimov on 16.01.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HistoryBusinessLogic {
    func getHistory(request: History.GetHistoryData.Request)
    func getFiltredHistory(request: History.FilterData.Request)
}

protocol HistoryDataStore {
    var historyEntries: [HistoryEntry] { get set }
}

class HistoryInteractor: HistoryBusinessLogic, HistoryDataStore {
    
    var presenter: HistoryPresentationLogic?
    
    var worker: HistoryWorker?
    
    var historyEntries = [HistoryEntry]()

    // MARK: Do something (and send response to HistoryPresenter)

    func getHistory(request: History.GetHistoryData.Request) {
        ApiManager.shared.getHistoryData { [weak self] result in
            switch result {
            case .success(let response):
                print(response)
                self?.historyEntries = response.entries
                let response = History.GetHistoryData.Response(
                    entries: response.entries)
                self?.presenter?.presentHistory(response: response)
            case .failure(_):
                //TODO: show some error
                break
            }
        }
        
    }

    func getFiltredHistory(request: History.FilterData.Request) {
//        worker = HistoryWorker()
//        worker?.doSomeOtherWork()
//
//        let response = History.FilterData.Response()
//        presenter?.presentFiltredHistory(response: response)
    }
}
