//
//  CreateNewEntryWorker.swift
//  Renter
//
//  Created by Oleg Efimov on 16.01.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

struct NumerousUserInput {
    let cold: Double
    let hot: Double
    let day: Double
    let night: Double
}

struct NewEntryConvertedInput {
    let plan: NumerousUserInput
    let meters: NumerousUserInput
}

enum ConvertError: Error {
    case invalidData
}

class CreateNewEntryWorker {
    func convertStringToDouble(_ request: CreateNewEntry.SaveNewEntry.Request) throws -> NewEntryConvertedInput {
        guard let coldPlan = Double(request.plan.cold),
              let hotPlan = Double(request.plan.hot),
              let dayPlan = Double(request.plan.day),
              let nightPlan = Double(request.plan.night),
              let cold = Double(request.meters.cold),
              let hot = Double(request.meters.hot),
              let day = Double(request.meters.day),
              let night = Double(request.meters.night)
        else {
            throw ConvertError.invalidData
        }
        return NewEntryConvertedInput(
            plan: NumerousUserInput(
                cold: coldPlan,
                hot: hotPlan,
                day: dayPlan,
                night: nightPlan),
            meters: NumerousUserInput(
                cold: cold,
                hot: hot,
                day: day,
                night: night))
    }
}
