//
//  CreateNewEntryRouter.swift
//  Renter
//
//  Created by Oleg Efimov on 16.01.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CreateNewEntryRoutingLogic {
    func routeToPreviousScreen()
}

protocol CreateNewEntryDataPassing {
    var dataStore: CreateNewEntryDataStore? { get }
}

class CreateNewEntryRouter: NSObject, CreateNewEntryRoutingLogic, CreateNewEntryDataPassing {
    weak var viewController: CreateNewEntryViewController?
    var dataStore: CreateNewEntryDataStore?

    func routeToPreviousScreen() {
        DispatchQueue.main.async {
            self.viewController?.navigationController?.popViewController(animated: true)
        }
    }
}
