//
//  CreateNewEntryPresenter.swift
//  Renter
//
//  Created by Oleg Efimov on 16.01.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreateNewEntryPresentationLogic {
    func presentCurrentPlan(response: CreateNewEntry.GetMeters.Response)
    func presentTransactionStatus(response: CreateNewEntry.SaveNewEntry.Response)
}

class CreateNewEntryPresenter: CreateNewEntryPresentationLogic {
    weak var viewController: CreateNewEntryDisplayLogic?

    // MARK: Parse and calc respnse from CreateNewEntryInteractor and send simple view model to CreateNewEntryViewController to be displayed

    func presentCurrentPlan(response: CreateNewEntry.GetMeters.Response) {
//        let viewModel = CreateNewEntry.GetMeters.ViewModel()
//        viewController?.displayCurrentPlan(viewModel: viewModel)
    }

    func presentTransactionStatus(response: CreateNewEntry.SaveNewEntry.Response) {
//        let viewModel = CreateNewEntry.SomethingElse.ViewModel()
//        viewController?.displayTransactionStatus(viewModel: viewModel)
    }
}
