//
//  CreateNewEntryWorker.swift
//  Renter
//
//  Created by Oleg Efimov on 16.01.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

struct NumerousUserInput {
    let cold: Double
    let hot: Double
    let day: Double
    let night: Double
}

struct NewEntryConvertedInput {
    let plan: NumerousUserInput
    let meters: NumerousUserInput
}

class CreateNewEntryWorker {
    func convertStringToDouble(_ request: CreateNewEntry.SaveNewEntry.Request) throws -> NewEntryConvertedInput {
        NewEntryConvertedInput(
            plan: NumerousUserInput(
                cold: Double(request.plan.cold)!,
                hot: Double(request.plan.hot)!,
                day: Double(request.plan.day)!,
                night: Double(request.plan.night)!),
            meters: NumerousUserInput(
                cold: Double(request.meters.cold)!,
                hot: Double(request.meters.hot)!,
                day: Double(request.meters.day)!,
                night: Double(request.meters.night)!))
    }
}
