//
//  CreateNewEntryModels.swift
//  Renter
//
//  Created by Oleg Efimov on 16.01.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CreateNewEntry {
    // MARK: Use cases

    enum GetMeters {
        struct Request {

        }

        struct Response {

        }

        struct ViewModel {
            let cold: Double
            let hot: Double
            let day: Double
            let night: Double
        }
    }
    
    enum SaveNewEntry {
        struct Request {
            let cold: Double
            let hot: Double
            let day: Double
            let night: Double
        }

        struct Response {
            let isSuccess: Bool
            //some model
        }

        struct ViewModel {

        }
    }
}
